Go
codecrafters-io/build-your-own-git pull request #13
Opened 2022-10-15 05:56 UTC by nikandfor

2022-10-15 20:23 UTC, rohitpaulk requested changes

2022-10-15 20:23 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func parseCommitTreeFlags(args []string) (commitTreeParams, error) {
@nikandfor would it be possible to use https://pkg.go.dev/flag#FlagSet.Parse here? Looks like that's designed for this use-case, no? The for-loop parsing seems pretty low-level to me, distracts from the overall goal

2022-10-15 20:23 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	buf = now.AppendFormat(buf, " -0700\n")
What is the -0700 here?

2022-10-15 20:23 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func commitTreeCmd(args []string) error {
Just noticed this: the file names are inconsistent, some have `_command` appended and some don't. 

<img width="303" alt="Screenshot 2022-10-15 at 21 03 28" src="https://user-images.githubusercontent.com/3893573/196005624-e1b92d30-e3fc-4769-b65d-c877e5d95b9c.png">

Can we use the `<whatever>_command.go` format for all of them please?

2022-10-15 20:23 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	if message != "" && message[len(message)-1] != '\n' {
I think we should check for `message != ""` early on and complain, like Git does: 

<img width="464" alt="Screenshot 2022-10-15 at 21 11 08" src="https://user-images.githubusercontent.com/3893573/196005843-c3cd977a-7873-4f10-b73a-f10c5dcf3e68.png">

2022-10-15 20:23 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +		buf = append(buf, '\n')
Does this match actual Git behaviour? What happens if the commit message had two newlines at the end? Would it keep two in the file?

My guess would be that either the message is written verbatim (including the newlines), or the message is written with all trailing newlines trimmed.

2022-10-15 20:23 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	hash, err := object.Store(bytes.NewReader(buf), "commit", int64(len(buf)))
Like how clean this is!

2022-10-15 20:25 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func parseCommitTreeFlags(args []string) (commitTreeParams, error) {
I agree, I'll change it to the flag.Parse.

2022-10-15 20:27 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	buf = now.AppendFormat(buf, " -0700\n")
It's a timezone in a git compatible format.

Why it's a -0700, it's a Go time formatting. One of the things which are not as clear in go.
https://pkg.go.dev/time#pkg-constants

2022-10-15 20:29 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func commitTreeCmd(args []string) error {
I was actually going to rename them all to <whatever>.go in the separate PR since we only hame main and commands here. It's don't needed to name everything command if we only have commands. What do you think?

2022-10-15 20:33 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	if message != "" && message[len(message)-1] != '\n' {
We have such a complain in flag parsing function. Yet I think it's a good practice to double check a little things that can lead to a crash if something changed in the code later.

2022-10-15 20:39 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +		buf = append(buf, '\n')
I'm adding newline here if it wasn't there. So when you inspect commit object content it always ends on newline.

The actual git seems to do the same (although I haven't checked the source code) as when you do cat-file <commit_hash> you get
```
$ git cat-file -p 73c857eef3a475f1a28b9e62c0a7567fd3773388
tree fa6da6ab077ab1418dd69e268cac72c6155169aa
parent 30f0fffac2e96fa5d067f08f63d07eecb3d1a2cf
author Paul Kuruvilla <rohitpaulk@gmail.com> 1665251854 +0100
committer Paul Kuruvilla <rohitpaulk@gmail.com> 1665251854 +0100

update sync starter repos script
air@01:34:06:course-sdk$
```

instead of
```
$ git cat-file -p 73c857eef3a475f1a28b9e62c0a7567fd3773388
tree fa6da6ab077ab1418dd69e268cac72c6155169aa
parent 30f0fffac2e96fa5d067f08f63d07eecb3d1a2cf
author Paul Kuruvilla <rohitpaulk@gmail.com> 1665251854 +0100
committer Paul Kuruvilla <rohitpaulk@gmail.com> 1665251854 +0100

update sync starter repos scriptair@01:34:06:course-sdk$
```

Yet it should be done in a bit more obvious way, I'll fix it.

2022-10-15 20:39 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func commitTreeCmd(args []string) error {
I feel like to beginners it'd be a bit more obvious if the file is named `_command.go`. Having `init.go` and `main.go` could be confusing, for example. I might be overthinking this though 🙂

2022-10-15 20:42 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	buf = now.AppendFormat(buf, " -0700\n")
Ah, got it. Looks like it's picking the current timezone though? I'm in +1 GMT, for example. 

<img width="733" alt="Screenshot 2022-10-15 at 21 41 36" src="https://user-images.githubusercontent.com/3893573/196006786-a9babc34-5196-4971-8311-e39ed03c5d74.png">

2022-10-15 20:43 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func commitTreeCmd(args []string) error {
Clarity is more important than clearness, lets rename it. But I would do it in a separate PR to have smaller diffs and to make it harder to miss something.

2022-10-15 20:44 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func commitTreeCmd(args []string) error {
Yep, separate PR is a good idea!

2022-10-15 20:46 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	buf = now.AppendFormat(buf, " -0700\n")
Yes, Go uses format-by-example instead of format-by-%-codes. And 7 means timezone, while 3 or 15 means hours, for example.

"2006-01-02T15:04:05Z07:00"
"Mon, 02 Jan 2006 15:04:05 -0700"

2022-10-15 20:56 UTC, rohitpaulk commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	buf = now.AppendFormat(buf, " -0700\n")
Aha.. interesting. Didn't realize that it is shorthand for the current timezone. Thanks for clarifying!

Now, getting back to the code: I wonder if it's be clearer to use `time.Format` instead of `time.AppendFormat`? 

i.e.: 

```go
fmt.Appendf(buf, "author %s <%s> %d %d\n", name, email, now.Unix(), now.Format("0700"))
```

2022-10-15 21:04 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +	buf = now.AppendFormat(buf, " -0700\n")
Yes, I agree.

2022-10-19 05:09 UTC, nikandfor commented on solutions/go/create_commit/code/cmd/mygit/commit_tree.go
> +func parseCommitTreeFlags(args []string) (commitTreeParams, error) {
flag package doesn't support flags after non-flag arguments, so even using it requires some work around. Yet it's a bit better now.

2022-10-20 20:04 UTC, rohitpaulk approved these changes

2022-10-20 20:33 UTC, merged