update go template project structure
codecrafters-io/build-your-own-git pull request #8
Opened 2022-10-02 12:44 UTC by nikandfor

* moved main package from ./app to ./cmd/mygit
* updated your_git.sh
* added go.mod

2022-10-02 13:58 UTC, nikandfor commented
I've committed with that commit applied so I need it in CI pipeline to be successful here.

https://github.com/codecrafters-io/course-sdk/pull/3

2022-10-07 12:51 UTC, rohitpaulk requested changes
Hey @nikandfor! 

Primary issue to resolve here would be for the diffs to be presentable. Every PR gets deployed automatically to production. 

I just realized that I might've communicated this wrongly on Slack: 

<img width="509" alt="Screenshot 2022-10-07 at 13 45 08" src="https://user-images.githubusercontent.com/3893573/194556757-bd37aa3b-3ff0-4950-9ead-581ceb1a200e.png">

By "minimal" changes, I meant to say that we don't have to "refactor" code from the future stages right now, but we do need to make the changes required to make the diffs presentable. 

If it seems like a lot of wasted work to make the changes to future stages and you'd rather commit all refactored solutions at once, that's fine too. Upto you how you want to handle this, only constraint is that any diffs that land on the `master` branch should be presentable to users.

2022-10-07 12:51 UTC, rohitpaulk commented on starter_templates/go/your_git.sh
> +"$tmpFile" "$@"
Let's keep the exec call as before - we've seen problems (can't remember what exactly atm, but git history might have details) when not using it

2022-10-07 12:51 UTC, rohitpaulk commented on starter_templates/go/go.mod
> +go 1.16
Should this be 1.19?

2022-10-07 12:51 UTC, rohitpaulk commented on starter_templates/go/go.mod
> +module git.codecrafters.io/go-git
Assuming this has no bearing on functionality, let's make this line: 

```suggestion
module github.com/codecrafters-io/git-starter-go
```

2022-10-07 12:51 UTC, rohitpaulk commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
```suggestion
	// "os"
```

2022-10-07 12:51 UTC, rohitpaulk commented on starter_templates/go/cmd/mygit/main.go
> +	//	switch command := os.Args[1]; command {
```suggestion
	// switch command := os.Args[1]; command {
```

(similar changes for other commented lines in this file. The whole "block" should be indented by `//` followed by a single space).

2022-10-07 12:51 UTC, rohitpaulk commented on solutions/go/read_blob/diff/your_git.sh.diff
> ++go build -o "$tmpFile" $(dirname "$0")/app/*.go
@nikandfor let's review all these diffs carefully and ensure they are good for production - I'd expect changes from stage 1 to be propagated to all `your_git.sh` files so that a diff is never shown

2022-10-07 12:51 UTC, rohitpaulk commented on solutions/go/read_blob/diff/go.mod.diff
> +-module git.codecrafters.io/go-git
We don't want this showing up as a diff - the diffs are the only content users see in the app, and they must only contain changes relevant to the particular stage

2022-10-07 12:51 UTC, rohitpaulk commented on solutions/go/read_blob/diff/cmd/mygit/main.go.diff
> +-
Same here - let's make changes to the other stages so that the diffs are appropriate. It's okay to not "cleanup" code from the future stages (that can be left for future PRs), but we need the diffs to be presentable to users

2022-10-07 15:53 UTC, nikandfor commented on starter_templates/go/your_git.sh
> +"$tmpFile" "$@"
git history starts from a big "copy from docker" commit where exec already exists.
I've removed it to make trap working. Otherwise temporary files kept building up.
But this is not so important, I'll return it back.

2022-10-07 15:55 UTC, nikandfor commented on starter_templates/go/go.mod
> +go 1.16
No I've set the smallest supported version. This will make newer language features to not to compile even if using new compiler. But this doesn't work for stdlib changes.

2022-10-07 15:56 UTC, rohitpaulk commented on starter_templates/go/your_git.sh
> +"$tmpFile" "$@"
Ah, got it - yeah, figured this might be related to `trap`. 

Here's the old discussion I was referring to re: why exec is needed: https://github.com/codecrafters-io/languages/pull/31#discussion_r446638753.

2022-10-07 16:01 UTC, nikandfor commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
Uncomment script doesn't reformat the go code according to gofmt standard and as a result we get incorrectly formatted starter code. There are spaces instead of tabs and closing bracket appears in the wrong column.

As I understood uncomment script just removes slashes and spaces before them. So having all the needed tabs after slashes makes init stage correctly formatted.

2022-10-07 16:04 UTC, nikandfor commented on solutions/go/read_blob/diff/your_git.sh.diff
> ++go build -o "$tmpFile" $(dirname "$0")/app/*.go
Yes, this is the reason I wanted to remove the following stages and add them back merging with previous step code manually.

But I can propagate changes either.

2022-10-07 16:05 UTC, rohitpaulk commented on starter_templates/go/go.mod
> +go 1.16
Ah okay. Just so that I'm understanding this correctly - if a user tries to use a language feature that's only available in Go 1.19, would they be able to?

2022-10-07 16:07 UTC, nikandfor commented on solutions/go/read_blob/diff/go.mod.diff
> +-module git.codecrafters.io/go-git
I've only made the CI not complain about the latter stages. I was planning to update and commit stages in different PRs.

2022-10-07 16:07 UTC, nikandfor commented on solutions/go/read_blob/diff/go.mod.diff
> +-module git.codecrafters.io/go-git
This was about init stage only.

2022-10-07 16:08 UTC, nikandfor commented on solutions/go/read_blob/diff/cmd/mygit/main.go.diff
> +-
ok

2022-10-07 16:14 UTC, nikandfor commented on starter_templates/go/go.mod
> +go 1.16
Nope, the compiler will complain about it. But our older version tests will work in return.

2022-10-07 16:15 UTC, rohitpaulk commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
Good observation. I thought we had a rule in place to verify that all Go code passes `gofmt` (we do have this for JS & Rust), maybe that isn't true. Will check. 

The uncommenter is _supposed_ to keep spaces/tabs intact and only remove "// ": 

https://github.com/codecrafters-io/course-sdk/blob/7ba30ee84dd028d0c95222e06f22a89ff126fb96/lib/uncommenter.rb#L62

[This](https://github.com/codecrafters-io/course-sdk/blob/7ba30ee84dd028d0c95222e06f22a89ff126fb96/lib/uncommenter.rb#L12) is the pattern used in that replacement.

I'll test this on another course repo and report back.

2022-10-07 16:18 UTC, rohitpaulk commented on starter_templates/go/go.mod
> +go 1.16
Ah, okay got it. Sounds reasonable for now! I suppose at some point in the future it might make sense to deprecate 1.16 like we did with 1.13.

2022-10-07 16:20 UTC, nikandfor commented on starter_templates/go/your_git.sh
> +"$tmpFile" "$@"
Alternative, although it's quite more complex
https://unix.stackexchange.com/questions/146756/forward-sigterm-to-child-in-bash

2022-10-07 16:29 UTC, nikandfor commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
The pattern includes leading spaces
https://github.com/codecrafters-io/course-sdk/blob/7ba30ee84dd028d0c95222e06f22a89ff126fb96/lib/uncommenter.rb#L3

2022-10-07 16:37 UTC, nikandfor commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
Ah, there is grouping, got it

2022-10-07 16:37 UTC, rohitpaulk commented on starter_templates/go/your_git.sh
> +"$tmpFile" "$@"
Nice find! I think something like that would be a good choice if this was internal and not exposed to users - but since this appears in the starter code, it could pretty confusing for users 🙂

2022-10-07 16:42 UTC, rohitpaulk commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
@nikandfor there are two capturing groups in the pattern, and only the second match is replaced - so any leading spaces/tabs should be left intact. 

To make this easier and less error-prone in the future, I've added a `gofmt` lint step to our tests [here](https://github.com/codecrafters-io/course-sdk/blob/30f0fffac2e96fa5d067f08f63d07eecb3d1a2cf/.github/workflows/test-course-definition.yml#L69).

Verified that the Redis course's `main.go` file passes those tests. 

Here's how that file looks (with spaces & tabs highlighted): 

<img width="846" alt="Screenshot 2022-10-07 at 17 34 47" src="https://user-images.githubusercontent.com/3893573/194604409-d660b503-e77c-48d0-866a-c2577572d6aa.png">

So that's `<TAB>//<SPACE>content_to_uncomment`.

Could you try the same here and see if that works? Any new commits pushed will automatically run `gofmt` and verify the structure is correct.

2022-10-07 16:43 UTC, rohitpaulk commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
(Sorry, replied before I saw your comment 🙂)

2022-10-07 17:54 UTC, nikandfor commented on starter_templates/go/cmd/mygit/main.go
> +	//	"os"
Thanks for the explanation anyway.

I found why there was a problem. It was bad formatted in a starter template.

https://github.com/codecrafters-io/build-your-own-git/blob/0bdc768f45133e5ca4aaf58b4d081064c61f7af3/starter_templates/go/app/main.go#L28

2022-10-07 19:28 UTC, nikandfor commented
In general in Go short variable names preferred: https://github.com/golang/go/wiki/CodeReviewComments#variable-names

So if we have a function on 40 lines and have variable like `objectFilePath` which we use only once in the next line this name is not common.

2022-10-07 19:42 UTC, nikandfor commented
@rohitpaulk  I've made some changes, could you give some feedback?

* `Mkdir` -> `MkdirAll` - it allows the program to finish successfully even if we already have some of the directories. Original git reinitializes repo with no error if it existed.
* Printed errors to stderr instead of stdout. This is a common practice for command line tools. This is especially useful when we use command output in a pipe and can lose an error message.
* split read blob command into a few smaller functions, each with fewer lines. Added Close calls, wrapped errors and made variable names a bit shorter.

Some parts could look a bit too complex like closing the file. But this little complexity is required for reliability.
```
    defer func() {
        e := file.Close()
        if err == nil && e != nil {
            err = fmt.Errorf("close file: %w", e)
        }
    }()
```

2022-10-07 19:52 UTC, nikandfor commented
At the end of stage 7, we will have a pretty big and complex app. And it will be reasonable to split it into smaller packages.

So choosing between smaller diffs (between stages) and simpler code in the first stages (it's not common to make multiple packages with a single function to solve a simple task), which is preferable?

2022-10-08 18:10 UTC, rohitpaulk commented
@nikandfor the points you mentioned above seem reasonable! 

I like how the rule around shorter variable names is phrased. Method receivers, and common things like readers can have short names, the more unusual something is the more descriptive the name should be. The current structure you have going looks good.

> At the end of stage 7, we will have a pretty big and complex app. And it will be reasonable to split it into smaller packages.

> So choosing between smaller diffs (between stages) and simpler code in the first stages (it's not common to make multiple packages with a single function to solve a simple task), which is preferable?

Simpler code in the first stages is preferable 🙂 The progressive "refactoring" in further stages is a good opportunity to educate people about code organization in Go, and in general feedback has been that users appreciate this.

Note that we won't need to do solutions for stage 7 of Git (it's pretty involved, and will likely be moved into a ["challenge extension"](https://app.codecrafters.io/vote/challenge-extension-ideas?course=git) later. Once we're done with solutions until stage 6 we can move on to other challenges. Not sure which at the moment, but I'll let you know once we're close to completion of stage 6.

2022-10-08 18:10 UTC, rohitpaulk commented
Just adding a checklist for myself to review the final diffs: 

- [ ] Stage 1
- [ ] Stage 2
- [ ] Stage 3
- [ ] Stage 4

2022-10-08 18:14 UTC, rohitpaulk commented on solutions/go/read_blob/diff/cmd/mygit/cat_file_command.go.diff
> ++	if len(blobSha) < 4 {
@nikandfor assuming this is supposed to check for the SHA length - should this be `len(blobSha) != 40`?

2022-10-08 18:15 UTC, rohitpaulk commented on solutions/go/read_blob/diff/cmd/mygit/cat_file_command.go.diff
> ++		return fmt.Errorf("bad object: %v", blobSha)
@nikandfor this isn't a "bad object", per-se - it's a bad SHA / object name. 

Here's what git says when a SHA is invalid: 

<img width="414" alt="Screenshot 2022-10-08 at 19 15 04" src="https://user-images.githubusercontent.com/3893573/194721739-9cb96bd0-d068-4c20-a65e-f230dc6bfaa8.png">

Can we do something similar here? Maybe `bad object name: %v`.

2022-10-08 18:19 UTC, rohitpaulk commented on solutions/go/create_blob/diff/README.md.diff
> ++The entry point for your Git implementation is in `app/main.go`. Study and
@nikandfor let's copy over the README from previous stages so that there's no diff here

2022-10-08 18:20 UTC, nikandfor commented on solutions/go/create_blob/diff/README.md.diff
> ++The entry point for your Git implementation is in `app/main.go`. Study and
Yes, I wasn't cleaning all the stages after read blob yet.

2022-10-08 18:22 UTC, rohitpaulk commented on solutions/go/create_blob/diff/cmd/mygit/main.go.diff
> ++		err = HashObject(os.Args[2:])
@nikandfor you can tackle this in future PRs if you want, just thought I'd add a note here - the naming should be consistent among command functions, I'd expect this to be `hashObjectCmd`

2022-10-08 18:24 UTC, rohitpaulk commented on solutions/go/create_blob/diff/README.md.diff
> ++The entry point for your Git implementation is in `app/main.go`. Study and
This specific case I'd fix now though - it can be confusing to users (given that the `app/main.go` file isn't even present). Refactoring code in further stages can of course be kept for future PRs.

2022-10-08 18:25 UTC, nikandfor commented on solutions/go/create_blob/diff/cmd/mygit/main.go.diff
> ++		err = HashObject(os.Args[2:])
yes, I'm moving by small steps.

2022-10-08 18:35 UTC, rohitpaulk approved these changes
Good to merge once the remaining minor comments are addressed 🎉

2022-10-08 19:40 UTC, nikandfor commented
If I haven't missed some propagation it's done.

2022-10-08 19:46 UTC, rohitpaulk commented
@nikandfor looks good to me! Feel free to merge whenever you're ready 👍

2022-10-08 19:56 UTC, merged